## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.6
  - nightly
notifications:
  email: false
git:
  depth: 99999999

## uncomment the following lines to allow failures on nightly julia
## (tests will run but not make your overall status red)
#matrix:
#  allow_failures:
#  - julia: nightly

addons:
  apt: # apt-get for linux
    packages:
    - liblapack-dev
    - libblas-dev
#before_script: # homebrew for mac
#  - if [ $TRAVIS_OS_NAME = osx ]; then brew install gcc; fi

before_script:
  - julia -e 'Pkg.clone("https://github.com/JuliaOpt/MathOptInterface.jl.git")'
  - julia -e 'Pkg.clone("https://github.com/JuliaOpt/MathOptInterfaceBridges.jl.git")'

## uncomment the following lines to override the default test script
script:
  - julia -e 'Pkg.init(); Pkg.clone(pwd()); Pkg.clone("https://github.com/JuliaOpt/CSDP.jl.git"); Pkg.build("CSDP"); Pkg.build("SemidefiniteOptInterface"); Pkg.test("SemidefiniteOptInterface"; coverage=true)'
after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("SemidefiniteOptInterface")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("SemidefiniteOptInterface")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
